/**
 * Turn the drawn egg bases into path data the generator can use.
 *
 *   bun scripts/egg-base.ts
 *   bun scripts/egg-base.ts --check
 *
 * `artwork/eggs/egg_base_1.svg` through `egg_base_3.svg` are the source: three
 * arrangements holding one, two and three eggs, drawn on the same 1024 artboard
 * the owl uses. Each egg is one closed path tagged `id="Egg-N"`, and N is the
 * order it is stacked in — Egg-1 at the back, Egg-3 in front — which is also
 * the order the shell tones are handed out in.
 *
 * The extraction is a regex rather than an XML parse on purpose. The input is
 * three files exported from one drawing tool, every egg is a bare `<path>`, and
 * a parser here would be a dependency the package does not otherwise have. If a
 * drawing ever stops matching, this fails loudly rather than writing half of
 * one.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const here = new URL("..", import.meta.url).pathname;
const out = resolve(here, "src/eggs/bases.generated.ts");

const EGG = /<path\s+id="Egg-(\d+)"\s+d="([^"]+)"/g;

/** Every egg in one drawing, in the order it is stacked. */
function eggsIn(file: string): string[] {
  const svg = readFileSync(resolve(here, "artwork/eggs", file), "utf8");

  const found = new Map<number, string>();
  for (const match of svg.matchAll(EGG)) found.set(Number(match[1]), match[2]!);

  if (found.size === 0) {
    throw new Error(
      `${file} has no <path id="Egg-N">. Did the export drop the ids?`
    );
  }

  // Numbered from 1 with no gaps, because the index is what picks a shell tone
  // and a gap would silently shift every egg after it onto the wrong one.
  const eggs: string[] = [];
  for (let i = 1; i <= found.size; i += 1) {
    const d = found.get(i);
    if (!d) throw new Error(`${file} has ${found.size} eggs but no Egg-${i}.`);
    eggs.push(d);
  }
  return eggs;
}

const bases = [
  eggsIn("egg_base_1.svg"),
  eggsIn("egg_base_2.svg"),
  eggsIn("egg_base_3.svg")
];

for (const [i, eggs] of bases.entries()) {
  if (eggs.length !== i + 1) {
    throw new Error(
      `egg_base_${i + 1}.svg holds ${eggs.length} eggs, expected ${i + 1}.`
    );
  }
}

const body = bases
  .map(
    (eggs) =>
      `  [\n${eggs.map((d) => `    ${JSON.stringify(d)},`).join("\n")}\n  ],`
  )
  .join("\n");

const file = `/**
 * Generated by scripts/egg-base.ts from artwork/eggs/ — do not edit.
 *
 * One entry per arrangement: index 0 holds one egg, index 2 holds three. Each
 * egg is closed path data on the 1024 artboard, back to front.
 */

export const EGG_BASES: readonly (readonly string[])[] = [
${body}
];
`;

if (process.argv.includes("--check")) {
  const current = readFileSync(out, "utf8");
  if (current !== file) {
    console.error("bases.generated.ts is stale. Run: bun scripts/egg-base.ts");
    process.exit(1);
  }
  console.log("egg bases up to date");
} else {
  writeFileSync(out, file);
  console.log(
    `wrote ${bases.reduce((n, e) => n + e.length, 0)} eggs across ${bases.length} bases`
  );
}
