/**
 * Pull the curated pattern tiles out of pattern.monster's own data.
 *
 *   bun scripts/egg-pattern.ts
 *   bun scripts/egg-pattern.ts --check
 *
 * The eggs are patterned with tiles from pattern.monster
 * (github.com/catchspider2002/svelte-svg-patterns, MIT). Upstream ships 330 of
 * them in one 970 kB module; `artwork/eggs/patterns.json` names the few dozen
 * that read as themselves at 32 px.
 *
 * Fetching rather than vendoring the module, because vendoring a megabyte to
 * keep forty tiles is a megabyte in every diff and every clone. A development
 * command: not part of `build`, and the file it writes is checked in.
 *
 * Everything upstream computes from its sliders is baked here. The generator
 * draws a tile; it does not know what a "colorCount" is.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const here = new URL("..", import.meta.url).pathname;
const out = resolve(here, "src/eggs/patterns.generated.ts");
const listFile = resolve(here, "artwork/eggs/patterns.json");

/** One entry of upstream's index, with the fields this needs. */
interface Upstream {
  slug: string;
  mode: "fill" | "stroke" | "stroke-join";
  /** Ink layers plus one for the tile's own background. */
  colors: number;
  maxStroke: number;
  width: number;
  height: number;
  /**
   * How much of `height` one row of the shape takes, for the tiles that stack
   * the same shape several times. Zero for everything else, and that zero is
   * what upstream branches on — so it is the flag as well as the number.
   */
  vHeight: number;
  /** The layers, back to front, separated by `~`. */
  path: string;
}

interface Curated {
  slug: string;
  /** How wide one repeat is drawn, in artboard units. */
  tile: number;
  /** Stroke weight in artboard units, before the seed scales the tile. */
  ink?: number;
  /** Rows to keep, for a tile that stacks them. Two is one row of shapes. */
  rows?: number;
}

/** The stroke weight a tile gets when it does not ask for one. */
const INK = 13;

const list = JSON.parse(readFileSync(listFile, "utf8")) as {
  source: string;
  revision: string;
  patterns: Curated[];
};

const url = `https://raw.githubusercontent.com/catchspider2002/svelte-svg-patterns/${list.revision}/src/routes/_index.js`;
const module_ = await (await fetch(url)).text();

// The file is `const index = [...]` and nothing else. Trimming the assignment
// off is enough, and JSON.parse then rejects anything that is not the array
// this expects — which is the check that matters if upstream ever restructures.
const body = module_
  .replace(/^\s*const index\s*=\s*/, "")
  .replace(/;?\s*(export default index;?)?\s*$/, "");
const upstream = new Map<string, Upstream>(
  (JSON.parse(body) as Upstream[]).map((p) => [p.slug, p])
);

/**
 * One curated entry, with everything upstream's UI would have decided baked in.
 *
 * The two branches are upstream's. A tile with a `vHeight` stacks rows of one
 * shape and can be cut down to fewer, which is how a five-row chevron becomes
 * one row of chevrons; a tile without one draws every layer it has.
 */
function bake(entry: Curated) {
  const p = upstream.get(entry.slug);
  if (!p) throw new Error(`pattern.monster has no "${entry.slug}" any more.`);

  const stacked = p.vHeight > 0;
  const rows = stacked ? Math.min(entry.rows ?? 2, p.colors) : p.colors;
  const layers = stacked ? rows - 1 : Math.max(1, p.colors - 1);

  const width = p.width;
  const height = stacked ? p.height - p.vHeight * (p.colors - rows) : p.height;

  const scale = entry.tile / width;
  const stroke = Math.round(((entry.ink ?? INK) / scale) * 100) / 100;
  if (p.mode !== "fill" && stroke > p.maxStroke) {
    console.warn(
      `${entry.slug}: stroke ${stroke} is past upstream's ${p.maxStroke} — check it looks right.`
    );
  }

  return {
    name: entry.slug,
    mode: p.mode === "stroke-join" ? "round" : p.mode,
    width,
    height,
    tile: entry.tile,
    stroke,
    layers: p.path.split("~").slice(0, layers)
  };
}

const baked = list.patterns.map(bake);

const seen = new Set<string>();
for (const p of baked) {
  if (seen.has(p.name)) throw new Error(`"${p.name}" is listed twice.`);
  seen.add(p.name);
}

const entries = baked
  .map(
    (p) =>
      `  {\n` +
      `    name: ${JSON.stringify(p.name)},\n` +
      `    mode: ${JSON.stringify(p.mode)},\n` +
      `    width: ${p.width},\n` +
      `    height: ${p.height},\n` +
      `    tile: ${p.tile},\n` +
      `    stroke: ${p.stroke},\n` +
      `    layers: [\n${p.layers.map((d) => `      ${JSON.stringify(d)},`).join("\n")}\n    ],\n` +
      `  },`
  )
  .join("\n");

const file = `/**
 * Generated by scripts/egg-pattern.ts from artwork/eggs/patterns.json — do not
 * edit.
 *
 * The tiles are pattern.monster's, used under its MIT licence:
 *
 *   Copyright (c) 2020-2023 Pattern Monster
 *   ${list.source}
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * To add one, put its slug in artwork/eggs/patterns.json and re-run the script.
 * Adding to the end costs nothing: the draw is keyed on the name, so an egg
 * that was not going to wear the new tile keeps the one it had.
 */

import type { EggPattern } from "./types";

export const EGG_PATTERNS: readonly EggPattern[] = [
${entries}
];
`;

if (process.argv.includes("--check")) {
  if (readFileSync(out, "utf8") !== file) {
    console.error(
      "patterns.generated.ts is stale. Run: bun scripts/egg-pattern.ts"
    );
    process.exit(1);
  }
  console.log("egg patterns up to date");
} else {
  writeFileSync(out, file);
  console.log(
    `wrote ${baked.length} patterns, ${(file.length / 1024).toFixed(1)} kB`
  );
}
