/**
 * Turn a drawing of an owl wearing something into just the something.
 *
 * The workflow this exists for: `--base` writes the bare bird as an SVG, you
 * open it, draw a hat on it, save it into `artwork/`, and this subtracts the
 * bird back out and leaves the hat. No measuring, no anchor point, no scale
 * factor — the hat is already in the coordinates the generator draws in,
 * because you drew it there.
 *
 *   bun scripts/owl-accessory.ts --base
 *   bun scripts/owl-accessory.ts --all
 *   bun scripts/owl-accessory.ts artwork/Winter_Hat.svg --slot head
 *
 * `--all` is the usual one. It rebuilds every accessory listed in
 * `artwork/accessories.json` and writes the registry, so a corrected drawing is
 * one command rather than a hand-edit.
 *
 * The bird it subtracts is generated on the spot from the same code that draws
 * avatars, not read from a file kept beside it. A stored copy is a copy that can
 * go stale, and a stale one fails in the worst way available: it stops matching,
 * every path survives the subtraction, and the accessory you get is an entire
 * second owl.
 *
 * Paths are matched on what they draw, not on how they are written down. A
 * drawing tool rewrites path data on the way out — it rounds numbers, it turns
 * a degenerate curve into `H`, it drops a redundant control point — so
 * comparing strings finds nothing at all. Each path is flattened into a
 * polyline instead and identified by its extent, its length and its area, none
 * of which care how the file spells them.
 *
 * Recolouring part of the bird counts as part of the accessory. A coat covers
 * the owl's arms, so the drawing paints the wings in the background's colour and
 * they disappear. Subtracting that path as "unchanged base" would throw the
 * intent away, so a matched path whose fill has moved is recorded as a repaint
 * instead — see `recolour` on Accessory.
 *
 * Keep the source drawings. They are a few kilobytes each, they are the only
 * record of how an accessory was positioned, and the day one needs a nudge the
 * alternative is redrawing it from the exported result.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";

import { readShapes, type Shape } from "./lib/svg-shapes";
import { simplifyPath } from "./lib/svg-simplify";
import {
  isIgnored,
  placementFor,
  weightsFor,
  type Placement,
  type Rarity,
} from "./lib/filename";

import * as owl from "../src/index";
import { INKS } from "../artwork/inks";

const root = path.resolve(import.meta.dir, "..");
const GENERATED = "src/accessories.generated.ts";

/**
 * The bird the script draws and subtracts.
 *
 * The palette is only there so the drawing is pleasant to work on; the
 * subtraction matches on geometry and ignores colour except where it has
 * changed. `blob` eyes and `tufts` ears because that is the drawn owl, and an
 * accessory positioned against any other expression would sit a little wrong on
 * this one.
 *
 * Every slot is emptied explicitly, and that is not belt and braces. Left to the
 * seed, the bird would wear whatever the accessories already in the registry
 * rolled for it — so the moment the first one landed, the bird being subtracted
 * stopped being bare and every drawing failed to match. It is emptied here so
 * the base cannot depend on what has been added since.
 */
const BARE = { expression: null, eyewear: null, head: null, neck: null, body: null };
const BASE = {
  palette: "teal",
  scheme: "day",
  ears: "tufts",
  size: 1024,
  wearing: BARE,
} satisfies owl.OwlOptions;

/**
 * Where each slot lands unless told otherwise.
 *
 * Spectacles go over the eyes, because that is what a drawing of spectacles
 * does — the lens is painted, and it covers the eye behind it. Use `overFace`
 * for a pair drawn as holes only, where the expression should show through.
 *
 * A garment goes on top of everything, collar included. It is drawn over the
 * bird rather than tucked behind it, which is what a coat does.
 */
const DEFAULT_LAYER: Record<owl.AccessorySlot, string> = {
  expression: "overFace",
  eyewear: "overEyes",
  head: "overAll",
  neck: "overAll",
  body: "overAll",
};

function header() {
  return (
    "/**\n" +
    " * Generated by scripts/owl-accessory.ts from artwork/ — do not edit.\n" +
    " *\n" +
    " * Each block is one drawing with the bird subtracted out of it. To change an\n" +
    " * accessory, change the drawing or its entry in artwork/accessories.json and\n" +
    " * run `bun scripts/owl-accessory.ts --all`.\n" +
    " */\n\n" +
    'import type { Accessory } from "./accessories";\n\n' +
    "export const GENERATED_ACCESSORIES: readonly Accessory[] = [\n"
  );
}

/* --- geometry ------------------------------------------------------------ */

/**
 * A path, walked and sampled into a polyline.
 *
 * Supports the commands a drawing tool actually emits for this artwork. Arcs
 * are not among them and are rejected rather than approximated — an accessory
 * that is subtly the wrong shape is harder to notice than one that refuses to
 * build.
 */
function flatten(d: string) {
  const tokens = d.match(/[MmLlHhVvCcSsQqTtAaZz]|-?\d*\.?\d+(?:e-?\d+)?/gi) || [];
  const points: Array<[number, number]> = [];
  let subpaths = 0;
  let i = 0;
  let x = 0;
  let y = 0;
  let sx = 0;
  let sy = 0;
  let command = "";
  const num = () => Number(tokens[i++]);

  /** Eight samples a curve: enough that two spellings of one arc agree. */
  const cubic = (x1: number, y1: number, x2: number, y2: number, x3: number, y3: number) => {
    for (let k = 1; k <= 8; k += 1) {
      const t = k / 8;
      const u = 1 - t;
      points.push([
        u * u * u * x + 3 * u * u * t * x1 + 3 * u * t * t * x2 + t * t * t * x3,
        u * u * u * y + 3 * u * u * t * y1 + 3 * u * t * t * y2 + t * t * t * y3,
      ]);
    }
    x = x3;
    y = y3;
  };

  while (i < tokens.length) {
    if (/[A-Za-z]/.test(tokens[i])) command = tokens[i++];
    const rel = command === command.toLowerCase();
    const c = command.toUpperCase();
    if (c === "A") throw new Error("arc commands are not supported");

    if (c === "Z") {
      points.push([sx, sy]);
      x = sx;
      y = sy;
      continue;
    }
    if (c === "M") {
      x = rel ? x + num() : num();
      y = rel ? y + num() : num();
      sx = x;
      sy = y;
      subpaths += 1;
      points.push([x, y]);
      command = rel ? "l" : "L";
      continue;
    }
    if (c === "L") {
      x = rel ? x + num() : num();
      y = rel ? y + num() : num();
      points.push([x, y]);
      continue;
    }
    if (c === "H") {
      x = rel ? x + num() : num();
      points.push([x, y]);
      continue;
    }
    if (c === "V") {
      y = rel ? y + num() : num();
      points.push([x, y]);
      continue;
    }
    if (c === "C") {
      const x1 = rel ? x + num() : num();
      const y1 = rel ? y + num() : num();
      const x2 = rel ? x + num() : num();
      const y2 = rel ? y + num() : num();
      cubic(x1, y1, x2, y2, rel ? x + num() : num(), rel ? y + num() : num());
      continue;
    }
    if (c === "Q") {
      const qx = rel ? x + num() : num();
      const qy = rel ? y + num() : num();
      const ex = rel ? x + num() : num();
      const ey = rel ? y + num() : num();
      cubic(
        x + (2 / 3) * (qx - x), y + (2 / 3) * (qy - y),
        ex + (2 / 3) * (qx - ex), ey + (2 / 3) * (qy - ey),
        ex, ey,
      );
      continue;
    }
    throw new Error(`unsupported path command "${command}"`);
  }
  return { points, subpaths };
}

/**
 * What a path draws, as a string two files can be compared on.
 *
 * Extent, perimeter and area. Serialisation changes none of them, and two
 * genuinely different shapes agreeing on all three is not something that
 * happens by accident.
 */
function shapeKey(d: string): string {
  const { points, subpaths } = flatten(d);
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  let length = 0;
  let area = 0;
  for (let k = 0; k < points.length; k += 1) {
    const [px, py] = points[k];
    if (px < minX) minX = px;
    if (py < minY) minY = py;
    if (px > maxX) maxX = px;
    if (py > maxY) maxY = py;
    const [qx, qy] = points[(k + 1) % points.length];
    length += Math.hypot(qx - px, qy - py);
    area += px * qy - qx * py;
  }
  const r = (n: number) => Math.round(n * 2) / 2;
  return [
    r(minX), r(minY), r(maxX), r(maxY),
    Math.round(length), Math.round(Math.abs(area) / 2), subpaths,
  ].join("|");
}

/** The frame itself, however it is spelled — a background rather than a hat. */
function isBackground(d: string): boolean {
  const { points } = flatten(d);
  const xs = points.map((p) => p[0]);
  const ys = points.map((p) => p[1]);
  return (
    Math.min(...xs) <= 0.5 && Math.min(...ys) <= 0.5 &&
    Math.max(...xs) >= 1023.5 && Math.max(...ys) >= 1023.5 &&
    points.length <= 12
  );
}

function paths(svg: string): Shape[] {
  return readShapes(svg).shapes;
}

/* --- the bird, and what each of its paths is ----------------------------- */

/**
 * Which palette role each of the bird's paths is painted from.
 *
 * Found by drawing the bird once in a palette of sentinel colours and reading
 * the fills back, rather than by hard-coding "the fourth path is a wing". The
 * generator stays free to reorder its own layers.
 */
const ROLES = [
  "background", "body", "face", "accent", "wing",
  "trimLight", "trim", "trimDeep", "trimSoft", "gold", "goldDeep",
] as const satisfies readonly owl.PaletteSlot[];
const sentinels: Partial<owl.OwlPalette> = Object.fromEntries(
  ROLES.map((role, i) => [role, `#${(i + 1).toString(16).padStart(6, "0")}`]),
);
const roleOf = new Map(
  paths(owl.owlAvatarSvg("base", { ...BASE, palette: sentinels })).map((p) => [
    shapeKey(p.d),
    ROLES[parseInt(p.fill.slice(1), 16) - 1],
  ]),
);

/**
 * Which part of the bird each of its paths belongs to.
 *
 * Colour cannot answer this — the eyes and the beak are both `accent` — and it
 * is the difference between "this drawing replaces the eyes" and "this drawing
 * paints the beak away too".
 */
const partOf = new Map(owl.owlPartPaths(BASE).map((p) => [shapeKey(p.d), p.part]));
const realPalette = owl.owlPalette(BASE.palette, BASE.scheme);
const roleByColour = new Map(
  Object.entries(realPalette).map(([role, hex]) => [hex.toLowerCase(), role]),
);
// The field is not part of the bird. It is a <rect> here and a <path> in a
// drawing, so it would never match anyway — leaving it in only makes every
// extraction report one path missing.
const baseFills = new Map(
  paths(owl.owlAvatarSvg("base", BASE))
    .filter((p) => !isBackground(p.d))
    .map((p) => [shapeKey(p.d), p.fill]),
);

/* --- extraction ---------------------------------------------------------- */

/** How light a hex is, for sorting. Rough on purpose; it only needs an order. */
function lightness(hex: string): number {
  const int = parseInt(hex.replace("#", ""), 16);
  return (((int >> 16) & 255) * 0.299 + ((int >> 8) & 255) * 0.587 + (int & 255) * 0.114) / 255;
}

/** Lightest first, which is the order the drawn accessories use their tones in. */
const LADDER: owl.PaletteSlot[] = ["trimSoft", "trimLight", "trim", "trimDeep", "accent"];

/** What extract needs to know about the accessory it is pulling out. */
interface ExtractOptions {
  name: string;
  slot: owl.AccessorySlot;
  /** Unset takes the slot's default from DEFAULT_LAYER. */
  layer?: string;
  weight: number;
  excludes: string[];
  places: number;
  tolerance: number;
  map: Map<string, owl.PaletteSlot>;
}

function extract(svg: string, label: string, opts: ExtractOptions) {
  if (/<g\b[^>]*\btransform=/.test(svg)) {
    throw new Error(
      `${label} has a <g transform=...> in it. Flatten the transforms in the drawing ` +
        "tool and export again — this script does not apply them, and an accessory " +
        "that is silently offset is worse than one that fails to build.",
    );
  }
  const viewBox = /viewBox="([^"]*)"/.exec(svg)?.[1];
  if (viewBox && viewBox.trim() !== "0 0 1024 1024") {
    throw new Error(
      `${label} has viewBox "${viewBox}". It has to be "0 0 1024 1024" — that is the ` +
        "frame the generator draws on, and it is the whole reason this works. Run with " +
        "--base to get a bird on the right frame and draw on that.",
    );
  }

  const seen = new Set<string>();
  const recolour: Partial<Record<owl.PaletteSlot, string>> = {};
  const hides = new Set<string>();
  const unplaceable = new Set<string>();
  const notes: string[] = [];

  const { shapes: drawn, unknown } = readShapes(svg);
  for (const tag of unknown) {
    notes.push(`<${tag}> is not something this can read — it was left out`);
  }

  const kept = drawn.filter((p) => {
    if (isBackground(p.d)) return false;
    const key = shapeKey(p.d);
    if (!baseFills.has(key)) return true;
    seen.add(key);

    // The shape is the bird's but the colour is not. Two different intentions
    // wear that disguise, and telling them apart needs to know which part it is.
    if (p.fill !== baseFills.get(key)) {
      const part = partOf.get(key);

      // An expression brings its own eyes, and paints the drawn ones out to say
      // so. Recorded as "do not draw them" rather than as a repaint: the eyes
      // and the beak share a colour, so repainting the role would take the beak
      // with it, and a plate-coloured disc is only invisible where the plate is
      // what is behind it.
      if (part === "eyes") {
        hides.add("eyes");
        return false;
      }

      const role = roleOf.get(key);
      const to = roleByColour.get(p.fill);
      if (!role) unplaceable.add(`${p.fill} — could not tell which part that is`);
      else if (!to) unplaceable.add(`${p.fill} — not one of the base owl's colours`);
      else recolour[role] = to;
    }
    return false;
  });

  const missed = [...baseFills.keys()].filter((k) => !seen.has(k)).length;
  if (missed > 0) {
    notes.push(
      `${missed} of the bird's ${baseFills.size} paths were not found — a layer was ` +
        "edited or moved, or this was not drawn on the base",
    );
  }
  for (const f of unplaceable) notes.push(`repainted in a colour this cannot place: ${f}`);
  if (kept.length === 0 && Object.keys(recolour).length === 0 && hides.size === 0) {
    throw new Error(`${label}: nothing left after subtracting the bird`);
  }

  // Shrink after the subtraction, never before it: the bird is matched on its
  // geometry, and rounding the drawing first would move the very numbers being
  // matched on.
  const before = kept.reduce((n, p) => n + p.d.length, 0);
  for (const p of kept) p.d = simplifyPath(p.d, opts.places, opts.tolerance);
  const after = kept.reduce((n, p) => n + p.d.length, 0);

  const distinct = [
    ...new Set(kept.flatMap((p) => [p.fill, p.stroke].filter(Boolean))),
  ].sort((a, b) => lightness(b) - lightness(a));
  const roles = new Map<string, owl.PaletteSlot>();
  distinct.forEach((hex, i) => {
    roles.set(hex, opts.map.get(hex) ?? LADDER[Math.min(i, LADDER.length - 1)]);
  });

  const layer = opts.layer ?? DEFAULT_LAYER[opts.slot] ?? "overAll";
  const repaints = Object.entries(recolour);
  const literal =
    `  {\n` +
    `    name: "${opts.name}",\n` +
    `    slot: "${opts.slot}",\n` +
    `    layer: "${layer}",\n` +
    `    weight: ${opts.weight},\n` +
    (opts.excludes.length
      ? `    excludes: [${opts.excludes.map((e) => `"${e}"`).join(", ")}],\n`
      : "") +
    (hides.size
      ? `    hides: [${[...hides].map((h) => `"${h}"`).join(", ")}],\n`
      : "") +
    (repaints.length
      ? `    recolour: { ${repaints.map(([k, v]) => `${k}: "${v}"`).join(", ")} },\n`
      : "") +
    `    paths: [\n` +
    kept
      .map((p) => {
        const bits = [];
        if (p.fill) bits.push(`fill: "${roles.get(p.fill)}"`);
        if (p.stroke) {
          bits.push(`stroke: "${roles.get(p.stroke)}"`);
          bits.push(`strokeWidth: ${Math.round(p.strokeWidth * 10) / 10}`);
          if (p.linecap) bits.push(`linecap: "${p.linecap}"`);
          if (p.linejoin) bits.push(`linejoin: "${p.linejoin}"`);
        }
        if (p.evenodd) bits.push("evenodd: true");
        return `      { ${bits.join(", ")}, d: "${p.d}" },`;
      })
      .join("\n") +
    `\n    ],\n  },`;

  const pad = " ".repeat(20);

  // Colours the ink table has never seen. The caller collects these across
  // every drawing and stops, rather than shipping the lightness ladder's guess:
  // the ladder ranks a drawing's own colours against each other, so it has no
  // way to know that a mid-teal is `trim` here and `trimLight` in a lighter
  // drawing, and it gets that wrong more often than not.
  const guessed = distinct.filter((hex) => !opts.map.has(hex));
  const summary =
    `${opts.name.padEnd(18)} ${String(kept.length).padStart(2)} paths  ` +
    `${(after / 1000).toFixed(1).padStart(5)}kB` +
    (before > after ? ` -${String(Math.round((100 * (before - after)) / before)).padStart(2)}%` : "     ") +
    `  ${opts.slot}/${layer}` +
    (hides.size ? `  hides ${[...hides].join(" ")}` : "") +
    (repaints.length ? `  repaints ${repaints.map(([k, v]) => `${k}->${v}`).join(" ")}` : "") +
    (guessed.length
      ? `\n${pad}guessed: ${guessed.map((h) => `${h}->${roles.get(h)}`).join(" ")}`
      : "") +
    notes.map((n) => `\n${pad}warning: ${n}`).join("");

  const paint = (p: Shape, colour: (hex: string) => string) =>
    `<path d="${p.d}"${p.evenodd ? ' fill-rule="evenodd" clip-rule="evenodd"' : ""}` +
    ` fill="${p.fill ? colour(p.fill) : "none"}"` +
    (p.stroke
      ? ` stroke="${colour(p.stroke)}" stroke-width="${p.strokeWidth}"` +
        (p.linecap ? ` stroke-linecap="${p.linecap}"` : "") +
        (p.linejoin ? ` stroke-linejoin="${p.linejoin}"` : "")
      : "") +
    "/>";
  const body = kept.map((p) => paint(p, (hex) => hex)).join("");
  const stripped =
    `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" ` +
    `viewBox="0 0 1024 1024" fill="none">${body}</svg>\n`;

  return { literal, summary, stripped, roles, kept, paint, guessed };
}

/* --- arguments ----------------------------------------------------------- */

/** Flags that take a value. Everything else is a switch or a file name. */
const VALUED = new Set([
  "name", "slot", "layer", "weight", "map", "out", "excludes", "places", "tolerance",
]);

const options = new Map<string, string | true>();
const positional: string[] = [];
for (let i = 2; i < process.argv.length; i += 1) {
  const arg = process.argv[i];
  if (!arg.startsWith("--")) {
    positional.push(arg);
    continue;
  }
  const key = arg.slice(2);
  if (VALUED.has(key)) {
    options.set(key, process.argv[i + 1]);
    i += 1;
  } else {
    options.set(key, true);
  }
}
/**
 * A valued flag's value, or the fallback. Switches are read with `has`, so a
 * `true` sitting in the map here means the flag was given without its value and
 * the fallback is the right answer.
 */
function flag(name: string, fallback: string): string;
function flag(name: string, fallback?: string): string | undefined;
function flag(name: string, fallback?: string): string | undefined {
  const value = options.get(name);
  return typeof value === "string" ? value : fallback;
}

const has = (name: string) => options.get(name) === true;

/**
 * The palette roles an accessory's paths may ask for, so `--map` and the
 * manifest can be checked against them rather than trusted.
 *
 * A misspelled role used to travel all the way into accessories.generated.ts as
 * a fill nothing resolves, and the first sign of it was an owl wearing an
 * invisible hat.
 */
const PALETTE_ROLES = new Set<string>(ROLES);

function paletteRole(value: string, where: string): owl.PaletteSlot {
  if (!PALETTE_ROLES.has(value)) {
    console.error(`${where}: "${value}" is not a palette role. One of: ${ROLES.join(", ")}`);
    process.exit(1);
  }
  return value as owl.PaletteSlot;
}

function accessorySlot(value: string, where: string): owl.AccessorySlot {
  if (!(owl.ACCESSORY_SLOTS as string[]).includes(value)) {
    console.error(`${where}: "${value}" is not a slot. One of: ${owl.ACCESSORY_SLOTS.join(", ")}`);
    process.exit(1);
  }
  return value as owl.AccessorySlot;
}

/**
 * The ink table as the extractor wants it: lowercase hex to palette role.
 *
 * Typechecked at the source — artwork/inks.ts is TypeScript precisely so a
 * misspelled role is a red squiggle rather than something the run finds out
 * about — so there is nothing to validate here beyond the casing.
 */
const inks = new Map<string, owl.PaletteSlot>(
  Object.entries(INKS).map(([hex, role]) => [hex.toLowerCase(), role]),
);

/**
 * What the run did to each slot.
 *
 * Printed because the weights are no longer written down anywhere a person
 * reads. The fill rate is the number to check: it should match SLOT_PRESENCE
 * whatever was added, and if it has moved, the model is not doing its job.
 */
function reportSlots(
  placements: ReadonlyArray<{ name: string; slot: owl.AccessorySlot; rarity: Rarity }>,
  weights: ReadonlyMap<string, number>,
) {
  console.log("");
  for (const slot of owl.ACCESSORY_SLOTS) {
    const items = placements.filter((p) => p.slot === slot);
    if (!items.length) continue;

    const total = items.reduce((sum, i) => sum + weights.get(i.name)!, 0);
    const empty = owl.EMPTY_WEIGHT[slot];
    const fill = (100 * total) / (total + empty);
    const want = 100 * owl.SLOT_PRESENCE[slot];

    console.log(
      `${slot.padEnd(11)} ${String(items.length).padStart(2)} drawn   ` +
        `worn by ${fill.toFixed(1)}% of owls (asked for ${want.toFixed(1)}%)`,
    );
    const split = items
      .map((i) => `${i.name}:${weights.get(i.name)}${i.rarity === "common" ? "" : ` ${i.rarity}`}`)
      .join("  ");
    console.log(`            ${split}`);
  }
}

/* --- writing the bird ---------------------------------------------------- */

if (has("base")) {
  const out = flag("out", root);
  mkdirSync(out, { recursive: true });
  writeFileSync(path.join(out, "owl-base.svg"), owl.owlAvatarSvg("base", BASE) + "\n");
  writeFileSync(
    path.join(out, "owl-base-no-background.svg"),
    owl.owlAvatarSvg("base", { ...BASE, background: false }) + "\n",
  );
  const m = owl.OWL;
  console.log(`wrote owl-base.svg and owl-base-no-background.svg to ${out}`);
  console.log(`  eyes    (${m.cx - m.eyeGap / 2}, ${m.eyeY}) and (${m.cx + m.eyeGap / 2}, ${m.eyeY}), r ${m.eyeR}`);
  console.log(`  plate   x ${m.cx - m.faceHalf}..${m.cx + m.faceHalf}  y ${m.faceTop}..${m.faceTop + m.faceHeight}`);
  console.log(`  crown   y ${m.crown}`);
  console.log(`  widest  +/-${m.half} at y ${m.shoulder}`);
  process.exit(0);
}

/* --- the whole set, from the manifest ------------------------------------ */

if (has("all")) {
  const dir = flag("out", path.join(root, "artwork"));

  // Every drawing in the folder, in a fixed order. readdir's order is the
  // filesystem's and differs between machines, so sorting is what keeps the
  // generated file from changing depending on who ran the script.
  const files = readdirSync(dir)
    .filter((f) => f.toLowerCase().endsWith(".svg"))
    .filter((f) => !isIgnored(f))
    .sort();

  if (files.length === 0) {
    console.error(`No drawings in ${dir}. An accessory is an SVG dropped in there.`);
    process.exit(1);
  }

  // Read every filename before extracting anything. The weights depend on how
  // many drawings are in each slot, so they cannot be worked out one file at a
  // time — and a misnamed file should fail before the slow part rather than
  // seventeen extractions later.
  const placements: Array<{ file: string } & Placement> = [];
  const failures: string[] = [];
  for (const file of files) {
    try {
      placements.push({ file, ...placementFor(file, owl.ACCESSORY_SLOTS) });
    } catch (error) {
      failures.push(String(error instanceof Error ? error.message : error));
    }
  }
  if (failures.length) {
    console.error("These drawings do not say where they go:\n");
    for (const f of failures) console.error(`  ${f}\n`);
    process.exit(1);
  }

  const duplicates = placements
    .map((p) => p.name)
    .filter((name, i, all) => all.indexOf(name) !== i);
  if (duplicates.length) {
    console.error(`Two drawings would both be called ${[...new Set(duplicates)].join(", ")}.`);
    process.exit(1);
  }

  const weights = weightsFor(placements, owl.SLOT_PRESENCE, owl.EMPTY_WEIGHT.head);

  const blocks: string[] = [];
  const unknownInks = new Map<string, string[]>();
  for (const entry of placements) {
    const built = extract(readFileSync(path.join(dir, entry.file), "utf8"), entry.file, {
      name: entry.name,
      slot: entry.slot,
      layer: entry.layer,
      weight: weights.get(entry.name)!,
      excludes: entry.excludes,
      places: Number(flag("places", "1")),
      tolerance: Number(flag("tolerance", "0.4")),
      map: inks,
    });
    blocks.push(built.literal);
    console.log(built.summary);
    for (const hex of built.guessed) {
      if (!unknownInks.has(hex)) unknownInks.set(hex, []);
      unknownInks.get(hex)!.push(entry.name);
    }
  }

  // Collected across every drawing and reported once, so a new palette is one
  // paste rather than one failed run per colour.
  if (unknownInks.size > 0 && !has("guess")) {
    console.error(`\n${unknownInks.size} colour(s) are not in artwork/inks.ts.\n`);
    console.error("Add them, with the role each one should be repainted as:\n");
    for (const [hex, users] of unknownInks) {
      console.error(`  "${hex}": "trim",${" ".repeat(Math.max(1, 14 - hex.length))}// ${users.join(", ")}`);
    }
    console.error(
      `\nRoles: ${ROLES.join(", ")}.\n` +
        "Or run with --guess to let the lightness ladder pick, which is for\n" +
        "looking at a drawing rather than for anything committed.",
    );
    process.exit(1);
  }

  const content = header() + blocks.join("\n") + "\n];\n";

  reportSlots(placements, weights);

  /*
   * `--check` is for CI. The build regenerates this file, so a forgotten run is
   * harmless locally — but a stale one committed alongside a changed drawing
   * means the repository and the app disagree about what an owl is wearing, and
   * a build that quietly rewrites a tracked file is not where anyone should find
   * that out.
   */
  if (has("check")) {
    const target = path.join(root, GENERATED);
    const onDisk = existsSync(target) ? readFileSync(target, "utf8") : "";
    if (onDisk !== content) {
      console.error(
        `\n${GENERATED} is out of date.\n` +
          "Run `bun scripts/owl-accessory.ts --all` and commit the result.",
      );
      process.exit(1);
    }
    console.log(`\n${GENERATED} is up to date — ${placements.length} accessories`);
    process.exit(0);
  }

  writeFileSync(path.join(root, GENERATED), content);
  console.log(`\nwrote ${GENERATED} — ${placements.length} accessories`);
  process.exit(0);
}

/* --- one drawing --------------------------------------------------------- */

const input = positional[0];
if (!input) {
  console.error(
    "usage: owl-accessory.ts <drawing.svg> [--name n] [--slot eyes|head|neck|body]\n" +
      "                        [--layer behind|underFace|overFace|overEyes|overAll]\n" +
      "                        [--weight n] [--excludes neck,head]\n" +
      "                        [--map '#aabbcc=trim,...'] [--places n] [--tolerance n]\n" +
      "                        [--out dir] [--preview]\n" +
      "       owl-accessory.ts --all     rebuild every accessory from the manifest\n" +
      "       owl-accessory.ts --all --check  fail if that result is not committed\n" +
      "       owl-accessory.ts --base    write the bird to draw on",
  );
  process.exit(1);
}

// One drawing on its own, for looking at before it goes in the folder. The
// filename decides the same things it decides in --all, so what comes out here
// is what will come out there; the flags below only exist to try something
// without renaming the file first.
const fileName = path.basename(input);
let placement: Placement;
try {
  placement = placementFor(fileName, owl.ACCESSORY_SLOTS);
} catch (error) {
  // Not fatal on this path. A drawing being looked at may not have a name yet,
  // and --slot is right there.
  const flagged = flag("slot", "");
  if (!flagged) {
    console.error(String(error instanceof Error ? error.message : error));
    process.exit(1);
  }
  placement = {
    name: fileName.replace(/\.svg$/i, "").toLowerCase().replace(/[_\s]+/g, "-"),
    slot: accessorySlot(flagged, "--slot"),
    layer: "overAll",
    rarity: "common",
    excludes: [],
  };
}

const slot = flag("slot", "") ? accessorySlot(flag("slot", ""), "--slot") : placement.slot;
const name = flag("name", placement.name);

// --map on top of the ink table rather than instead of it, so trying a colour
// out does not mean restating every colour the drawing already uses.
const map = new Map(inks);
for (const pair of (flag("map", "") || "").split(",").filter(Boolean)) {
  const [hex, role] = pair.split("=");
  map.set(hex.trim().toLowerCase(), paletteRole(role.trim(), `--map ${pair}`));
}

const built = extract(readFileSync(path.resolve(input), "utf8"), fileName, {
  name,
  slot,
  layer: flag("layer", undefined) ?? placement.layer,
  // A single drawing has no slot to be a share of, so this is a placeholder.
  // --all is what sets the real one, from SLOT_PRESENCE and what else is drawn.
  weight: 0,
  excludes: placement.excludes,
  places: Number(flag("places", "1")),
  tolerance: Number(flag("tolerance", "0.4")),
  map,
});

if (built.guessed.length && !has("guess")) {
  console.error(`\n${built.guessed.length} colour(s) are not in artwork/inks.ts:\n`);
  for (const hex of built.guessed) console.error(`  "${hex}": "trim",`);
  console.error(`\nRoles: ${ROLES.join(", ")}. Or pass --guess to look at it anyway.`);
  process.exit(1);
}

const outDir = flag("out", path.dirname(path.resolve(input)));
mkdirSync(outDir, { recursive: true });
writeFileSync(path.join(outDir, `${name}.accessory.svg`), built.stripped);
writeFileSync(path.join(outDir, `${name}.accessory.ts.txt`), built.literal + "\n");
console.log(built.summary);
console.log(`  ${path.join(outDir, `${name}.accessory.svg`)}`);
console.log(`  ${path.join(outDir, `${name}.accessory.ts.txt`)}`);

if (has("preview")) {
  const bird = owl.owlAvatarSvg("preview", { ...BASE, size: 320 });
  const inner = bird.slice(bird.indexOf(">") + 1, bird.lastIndexOf("</svg>"));
  const recoloured = built.kept
    .map((p) => built.paint(p, (hex) => realPalette[built.roles.get(hex)!]))
    .join("");
  writeFileSync(
    path.join(outDir, `${name}.preview.html`),
    `<meta charset="utf-8"><body style="background:#1a1a22;margin:0;padding:16px">` +
      `<svg width="320" height="320" viewBox="0 0 1024 1024">${inner}${recoloured}</svg></body>\n`,
  );
  console.log(`  ${path.join(outDir, `${name}.preview.html`)}`);
}
