/**
 * Turn a drawing of an owl wearing something into just the something: `--base` writes the
 * bare bird, you draw on it, and this subtracts the bird back out. Keep the drawings.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";

import { extract, realPalette, ROLES } from "../src/lib/extract";
import { owlBaseSvg } from "../src/lib/owl-group";
import { readLedger, updateLedger, writeLedger } from "./lib/keys";
import {
  isIgnored,
  placementFor,
  weightsFor,
  type Placement,
  type Rarity,
} from "../src/lib/filename";

import * as owl from "../src/index";
import { INKS } from "../artwork/inks";

const root = path.resolve(import.meta.dir, "..");
const GENERATED = "src/accessories.generated.ts";

/**
 * The bird the script draws and subtracts. Defined in the package rather than here,
 * because the site's drawing guide hands the same bird out and the two must agree.
 */
const BASE = owl.OWL_BASE;

function header() {
  return (
    "/**\n" +
    " * Generated by scripts/owl-accessory.ts from artwork/ — do not edit.\n" +
    " *\n" +
    " * Each block is one drawing with the bird subtracted out of it. To change an\n" +
    " * accessory, change the drawing or its entry in artwork/accessories.json and\n" +
    " * run `bun scripts/owl-accessory.ts --all`.\n" +
    " */\n\n" +
    'import type { Accessory } from "./accessories";\n\n' +
    "export const GENERATED_ACCESSORIES: readonly Accessory[] = [\n"
  );
}


/* --- arguments ----------------------------------------------------------- */

/** Flags that take a value. Everything else is a switch or a file name. */
const VALUED = new Set([
  "name", "slot", "layer", "weight", "map", "out", "excludes", "places", "tolerance",
]);

const options = new Map<string, string | true>();
const positional: string[] = [];
for (let i = 2; i < process.argv.length; i += 1) {
  const arg = process.argv[i];
  if (!arg.startsWith("--")) {
    positional.push(arg);
    continue;
  }
  const key = arg.slice(2);
  if (VALUED.has(key)) {
    options.set(key, process.argv[i + 1]);
    i += 1;
  } else {
    options.set(key, true);
  }
}
/**
 * A valued flag's value, or the fallback. Switches are read with `has`, so a `true` here
 * means the flag was given without its value.
 */
function flag(name: string, fallback: string): string;
function flag(name: string, fallback?: string): string | undefined;
function flag(name: string, fallback?: string): string | undefined {
  const value = options.get(name);
  return typeof value === "string" ? value : fallback;
}

const has = (name: string) => options.get(name) === true;

/**
 * The palette roles an accessory's paths may ask for, so `--map` and the manifest are
 * checked rather than trusted. A misspelled role used to ship as an invisible hat.
 */
const PALETTE_ROLES = new Set<string>(ROLES);

function paletteRole(value: string, where: string): owl.PaletteSlot {
  if (!PALETTE_ROLES.has(value)) {
    console.error(`${where}: "${value}" is not a palette role. One of: ${ROLES.join(", ")}`);
    process.exit(1);
  }
  return value as owl.PaletteSlot;
}

function accessorySlot(value: string, where: string): owl.AccessorySlot {
  if (!(owl.ACCESSORY_SLOTS as string[]).includes(value)) {
    console.error(`${where}: "${value}" is not a slot. One of: ${owl.ACCESSORY_SLOTS.join(", ")}`);
    process.exit(1);
  }
  return value as owl.AccessorySlot;
}

/**
 * The ink table as the extractor wants it: lowercase hex to palette role. Typechecked at
 * the source, so there is nothing to validate here beyond the casing.
 */
const inks = new Map<string, owl.PaletteSlot>(
  Object.entries(INKS).map(([hex, role]) => [hex.toLowerCase(), role]),
);

/**
 * What the run did to each slot. The fill rate is the number to check: it should match
 * SLOT_PRESENCE whatever was added, and if it moved the model is not doing its job.
 */
function reportSlots(
  placements: ReadonlyArray<{ name: string; slot: owl.AccessorySlot; rarity: Rarity }>,
  weights: ReadonlyMap<string, number>,
) {
  console.log("");
  for (const slot of owl.ACCESSORY_SLOTS) {
    const items = placements.filter((p) => p.slot === slot);
    if (!items.length) continue;

    const total = items.reduce((sum, i) => sum + weights.get(i.name)!, 0);
    const empty = owl.EMPTY_WEIGHT[slot];
    const fill = (100 * total) / (total + empty);
    const want = 100 * owl.SLOT_PRESENCE[slot];

    console.log(
      `${slot.padEnd(11)} ${String(items.length).padStart(2)} drawn   ` +
        `worn by ${fill.toFixed(1)}% of owls (asked for ${want.toFixed(1)}%)`,
    );
    const split = items
      .map((i) => `${i.name}:${weights.get(i.name)}${i.rarity === "common" ? "" : ` ${i.rarity}`}`)
      .join("  ");
    console.log(`            ${split}`);
  }
}

/* --- writing the bird ---------------------------------------------------- */

if (has("base")) {
  const out = flag("out", root);
  mkdirSync(out, { recursive: true });
  writeFileSync(path.join(out, "owl-base.svg"), owlBaseSvg(BASE) + "\n");
  writeFileSync(
    path.join(out, "owl-base-no-background.svg"),
    owlBaseSvg({ ...BASE, background: false }) + "\n",
  );
  const m = owl.OWL;
  console.log(`wrote owl-base.svg and owl-base-no-background.svg to ${out}`);
  console.log(`  eyes    (${m.cx - m.eyeGap / 2}, ${m.eyeY}) and (${m.cx + m.eyeGap / 2}, ${m.eyeY}), r ${m.eyeR}`);
  console.log(`  plate   x ${m.cx - m.faceHalf}..${m.cx + m.faceHalf}  y ${m.faceTop}..${m.faceTop + m.faceHeight}`);
  console.log(`  crown   y ${m.crown}`);
  console.log(`  widest  +/-${m.half} at y ${m.shoulder}`);
  process.exit(0);
}

/* --- the whole set, from the manifest ------------------------------------ */

if (has("all")) {
  const dir = flag("out", path.join(root, "artwork"));

  // Every drawing in the folder, in a fixed order. readdir's order is the filesystem's, so
  // sorting is what keeps the generated file from depending on who ran the script.
  const files = readdirSync(dir)
    .filter((f) => f.toLowerCase().endsWith(".svg"))
    .filter((f) => !isIgnored(f))
    .sort();

  if (files.length === 0) {
    console.error(`No drawings in ${dir}. An accessory is an SVG dropped in there.`);
    process.exit(1);
  }

  // Read every filename before extracting anything: the weights depend on how many
  // drawings are in each slot, and a misnamed file should fail before the slow part.
  const placements: Array<{ file: string } & Placement> = [];
  const failures: string[] = [];
  for (const file of files) {
    try {
      placements.push({ file, ...placementFor(file, owl.ACCESSORY_SLOTS) });
    } catch (error) {
      failures.push(String(error instanceof Error ? error.message : error));
    }
  }
  if (failures.length) {
    console.error("These drawings do not say where they go:\n");
    for (const f of failures) console.error(`  ${f}\n`);
    process.exit(1);
  }

  const duplicates = placements
    .map((p) => p.name)
    .filter((name, i, all) => all.indexOf(name) !== i);
  if (duplicates.length) {
    console.error(`Two drawings would both be called ${[...new Set(duplicates)].join(", ")}.`);
    process.exit(1);
  }

  // A family competes for its slot as one thing, so a rarity belongs to the family. Two
  // variants disagreeing has no answer that does not silently ignore one tag.
  const rarityByFamily = new Map<string, Map<string, string[]>>();
  for (const p of placements) {
    if (!rarityByFamily.has(p.family)) rarityByFamily.set(p.family, new Map());
    const seen = rarityByFamily.get(p.family)!;
    if (!seen.has(p.rarity)) seen.set(p.rarity, []);
    seen.get(p.rarity)!.push(p.file);
  }
  const split = [...rarityByFamily].filter(([, seen]) => seen.size > 1);
  if (split.length) {
    for (const [family, seen] of split) {
      console.error(`${family} does not agree with itself about how rare it is:`);
      for (const [rarity, files] of seen) console.error(`  ${rarity.padEnd(9)} ${files.join(", ")}`);
    }
    console.error("\nA rarity belongs to the family. Tag every variant the same, or none of them.");
    process.exit(1);
  }

  const weights = weightsFor(placements, owl.SLOT_PRESENCE, owl.EMPTY_WEIGHT.head);

  /*
   * Keys before anything is extracted, so a run writes the ledger even if a later drawing
   * fails. A half-written ledger is recoverable; a key handed out twice is not.
   */
  const ledgerPath = path.join(dir, "keys.json");
  const ledger = updateLedger(readLedger(ledgerPath), placements.map((p) => p.name));
  writeLedger(ledgerPath, ledger);

  const blocks: string[] = [];
  const unknownInks = new Map<string, string[]>();
  for (const entry of placements) {
    const built = extract(readFileSync(path.join(dir, entry.file), "utf8"), entry.file, {
      name: entry.name,
      key: ledger.keys[entry.name]!,
      slot: entry.slot,
      layer: entry.layer,
      weight: weights.get(entry.name)!,
      excludes: entry.excludes,
      places: Number(flag("places", "1")),
      tolerance: Number(flag("tolerance", "0.4")),
      map: inks,
    });
    blocks.push(built.literal);
    console.log(built.summary);
    for (const hex of built.guessed) {
      if (!unknownInks.has(hex)) unknownInks.set(hex, []);
      unknownInks.get(hex)!.push(entry.name);
    }
  }

  // Collected across every drawing and reported once, so a new palette is one
  // paste rather than one failed run per colour.
  if (unknownInks.size > 0 && !has("guess")) {
    console.error(`\n${unknownInks.size} colour(s) are not in artwork/inks.ts.\n`);
    console.error("Add them, with the role each one should be repainted as:\n");
    for (const [hex, users] of unknownInks) {
      console.error(`  "${hex}": "trim",${" ".repeat(Math.max(1, 14 - hex.length))}// ${users.join(", ")}`);
    }
    console.error(
      `\nRoles: ${ROLES.join(", ")}.\n` +
        "Or run with --guess to let the lightness ladder pick, which is for\n" +
        "looking at a drawing rather than for anything committed.",
    );
    process.exit(1);
  }

  const content = header() + blocks.join("\n") + "\n];\n";

  reportSlots(placements, weights);

  /*
   * `--check` is for CI. A stale generated file committed with a changed drawing means the
   * repository and the app disagree about what an owl is wearing.
   */
  if (has("check")) {
    const target = path.join(root, GENERATED);
    const onDisk = existsSync(target) ? readFileSync(target, "utf8") : "";
    if (onDisk !== content) {
      console.error(
        `\n${GENERATED} is out of date.\n` +
          "Run `bun scripts/owl-accessory.ts --all` and commit the result.",
      );
      process.exit(1);
    }
    console.log(`\n${GENERATED} is up to date — ${placements.length} accessories`);
    process.exit(0);
  }

  writeFileSync(path.join(root, GENERATED), content);
  console.log(`\nwrote ${GENERATED} — ${placements.length} accessories`);
  process.exit(0);
}

/* --- one drawing --------------------------------------------------------- */

const input = positional[0];
if (!input) {
  console.error(
    "usage: owl-accessory.ts <drawing.svg> [--name n] [--slot eyes|head|neck|body]\n" +
      "                        [--layer behind|underFace|overFace|overEyes|overAll]\n" +
      "                        [--weight n] [--excludes neck,head]\n" +
      "                        [--map '#aabbcc=trim,...'] [--places n] [--tolerance n]\n" +
      "                        [--out dir] [--preview]\n" +
      "       owl-accessory.ts --all     rebuild every accessory from the manifest\n" +
      "       owl-accessory.ts --all --check  fail if that result is not committed\n" +
      "       owl-accessory.ts --base    write the bird to draw on",
  );
  process.exit(1);
}

// One drawing on its own, for looking at before it goes in the folder. The filename
// decides the same things it does in --all; the flags only avoid a rename first.
const fileName = path.basename(input);
let placement: Placement;
try {
  placement = placementFor(fileName, owl.ACCESSORY_SLOTS);
} catch (error) {
  // Not fatal on this path. A drawing being looked at may not have a name yet,
  // and --slot is right there.
  const flagged = flag("slot", "");
  if (!flagged) {
    console.error(String(error instanceof Error ? error.message : error));
    process.exit(1);
  }
  const fallbackName = fileName.replace(/\.svg$/i, "").toLowerCase().replace(/[_\s]+/g, "-");
  placement = {
    name: fallbackName,
    type: fallbackName,
    family: fallbackName,
    variant: "",
    slot: accessorySlot(flagged, "--slot"),
    layer: "overAll",
    rarity: "common",
    excludes: [],
  };
}

const slot = flag("slot", "") ? accessorySlot(flag("slot", ""), "--slot") : placement.slot;
const name = flag("name", placement.name);

// --map on top of the ink table rather than instead of it, so trying a colour
// out does not mean restating every colour the drawing already uses.
const map = new Map(inks);
for (const pair of (flag("map", "") || "").split(",").filter(Boolean)) {
  const [hex, role] = pair.split("=");
  map.set(hex.trim().toLowerCase(), paletteRole(role.trim(), `--map ${pair}`));
}

const built = extract(readFileSync(path.resolve(input), "utf8"), fileName, {
  name,
  slot,
  layer: flag("layer", undefined) ?? placement.layer,
  // A single drawing has no slot to be a share of, so this is a placeholder.
  // --all is what sets the real one, from SLOT_PRESENCE and what else is drawn.
  weight: 0,
  // A drawing looked at on its own has no key yet; --all is what assigns them.
  key: "--",
  excludes: placement.excludes,
  places: Number(flag("places", "1")),
  tolerance: Number(flag("tolerance", "0.4")),
  map,
});

if (built.guessed.length && !has("guess")) {
  console.error(`\n${built.guessed.length} colour(s) are not in artwork/inks.ts:\n`);
  for (const hex of built.guessed) console.error(`  "${hex}": "trim",`);
  console.error(`\nRoles: ${ROLES.join(", ")}. Or pass --guess to look at it anyway.`);
  process.exit(1);
}

const outDir = flag("out", path.dirname(path.resolve(input)));
mkdirSync(outDir, { recursive: true });
writeFileSync(path.join(outDir, `${name}.accessory.svg`), built.stripped);
writeFileSync(path.join(outDir, `${name}.accessory.ts.txt`), built.literal + "\n");
console.log(built.summary);
console.log(`  ${path.join(outDir, `${name}.accessory.svg`)}`);
console.log(`  ${path.join(outDir, `${name}.accessory.ts.txt`)}`);

if (has("preview")) {
  const bird = owl.owlAvatarSvg("preview", { ...BASE, size: 320 });
  const inner = bird.slice(bird.indexOf(">") + 1, bird.lastIndexOf("</svg>"));
  const recoloured = built.kept
    .map((p) => built.paint(p, (hex) => realPalette[built.roles.get(hex)!]))
    .join("");
  writeFileSync(
    path.join(outDir, `${name}.preview.html`),
    `<meta charset="utf-8"><body style="background:#1a1a22;margin:0;padding:16px">` +
      `<svg width="320" height="320" viewBox="0 0 1024 1024">${inner}${recoloured}</svg></body>\n`,
  );
  console.log(`  ${path.join(outDir, `${name}.preview.html`)}`);
}
